//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.28 at 02:37:59 PM AEST 
//


package au.com.unico.codingtest.soapservices.gcd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.com.unico.codingtest.soapservices.gcd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.com.unico.codingtest.soapservices.gcd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GcdList }
     * 
     */
    public GcdList createGcdList() {
        return new GcdList();
    }

    /**
     * Create an instance of {@link GcdSum }
     * 
     */
    public GcdSum createGcdSum() {
        return new GcdSum();
    }

    /**
     * Create an instance of {@link Gcd }
     * 
     */
    public Gcd createGcd() {
        return new Gcd();
    }

}
